/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TataUsaha;

import TataUsaha.Update.UpdateDataKelas;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import pelaporan.cell.TableActionCellEditor;
import pelaporan.cell.TableActionCellRender;
import pelaporan.cell.TableActionEvent;

/**
 *
 * @author Achmad
 */
public class DataKelas extends javax.swing.JFrame {

    /**
     * Creates new form DataKelas
     */
    public DataKelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataKelasTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        user = new java.awt.Label();
        searchDataSiswa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataKelasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA KELAS", "JURUSAN", "ANGKATAN", "ACTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataKelasTable.setRowHeight(40);
        DataKelasTable.setSelectionBackground(new java.awt.Color(187, 187, 187));
        jScrollPane1.setViewportView(DataKelasTable);

        btnBack.setBackground(new java.awt.Color(204, 51, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        user.setAlignment(java.awt.Label.RIGHT);
        user.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(204, 51, 255));
        user.setText("Name");

        searchDataSiswa.setText("Cari Nama kelas atau Jurusan");
        searchDataSiswa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchDataSiswaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchDataSiswaFocusLost(evt);
            }
        });
        searchDataSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchDataSiswaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HomeTataUsaha HomeTataUsahaFrame = new HomeTataUsaha();
        HomeTataUsahaFrame.setVisible(true);
        HomeTataUsahaFrame.pack();
        HomeTataUsahaFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void searchDataSiswaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDataSiswaFocusGained
        if (searchDataSiswa.getText().equals("Cari Nama kelas atau Jurusan")) {
            searchDataSiswa.setText("");
            searchDataSiswa.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchDataSiswaFocusGained

    private void searchDataSiswaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchDataSiswaFocusLost
        if (searchDataSiswa.getText().equals("")) {
            searchDataSiswa.setText("Cari Nama kelas atau Jurusan");
            searchDataSiswa.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchDataSiswaFocusLost

    private void searchDataSiswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchDataSiswaKeyReleased
        String searchText = searchDataSiswa.getText();

        String query = "SELECT k.id, k.nama_kelas, k.nama_jurusan, ta.gen "
                + "FROM kelas k "
                + "JOIN tahun_ajaran ta ON k.gen_id = ta.id "
                + "WHERE (m.nis LIKE ? OR m.nama LIKE ?)";

        // Buat model tabel
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "NAMA KELAS", "JURUSAN", "ANGKATAN", "ACTION"
        }, 0);

        try (Connection conn = koneksi.koneksiDB(); PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, "%" + searchText + "%");
            pstmt.setString(2, "%" + searchText + "%");

            try (ResultSet resultSet = pstmt.executeQuery()) {

                model.setRowCount(0);

                while (resultSet.next()) {
                    String id_kelas = resultSet.getString("id");
                    String namaKelas = resultSet.getString("nama_kelas");
                    String jurusan = resultSet.getString("jurusan");
                    String gen = resultSet.getString("gen");

                    model.addRow(new Object[]{id_kelas, namaKelas, jurusan, gen});
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Data gagal dimuat", "Error", JOptionPane.ERROR_MESSAGE);
        }

        DataKelasTable.setModel(model);

//        TableActionEvent event = new TableActionEvent() {
//            @Override
//            public void onEdit(int row) {
//                if (DataKelasTable.isEditing()) {
//                    DataKelasTable.getCellEditor().stopCellEditing();
//                }
//
////                String id_kelas = model.getValueAt(row, 0).toString();
//                String namaKelas = model.getValueAt(row, 1).toString();
//                String jurusan = model.getValueAt(row, 2).toString();
//                String gen = model.getValueAt(row, 3).toString();
//
//                UpdateDataKelas UpdateDataKelasForm = new UpdateDataKelas(userId, userName);
//                UpdateDataKelasForm.setVisible(true);
//            }
//
//            @Override
//            public void onDelete(int row) {
//                if (DataKelasTable.isEditing()) {
//                    DataKelasTable.getCellEditor().stopCellEditing();
//                }
//
//                DefaultTableModel model = (DefaultTableModel) DataKelasTable.getModel();
//                String nis = model.getValueAt(row, 0).toString();
//
//                int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data dengan NIS: " + nis + "?", "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
//
//                if (confirm == JOptionPane.YES_OPTION) {
//                    String query = "DELETE FROM murid WHERE nis = ?";
//
//                    try (Connection conn = koneksi.koneksiDB(); PreparedStatement preparedStatement = conn.prepareStatement(query)) {
//                        preparedStatement.setString(1, nis);
//                        int affectedRows = preparedStatement.executeUpdate();
//
//                        if (affectedRows > 0) {
//                            model.removeRow(row);
//                            JOptionPane.showMessageDialog(null, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Data gagal dihapus dari database.", "Error", JOptionPane.ERROR_MESSAGE);
//                        }
//                    } catch (SQLException e) {
//                        e.printStackTrace();
//                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
//                    }
//                }
//            }
//        };

        DataKelasTable.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
//        DataKelasTable.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event));
    }//GEN-LAST:event_searchDataSiswaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataKelasTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchDataSiswa;
    private java.awt.Label user;
    // End of variables declaration//GEN-END:variables
}
