/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TataUsaha.Update;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author Achmad
 */
public class UpdateDataTahunAjaran extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDataTahunAjaran
     */
    private int userId;
    private String tahun_ajaran, idTA, gen;

    public UpdateDataTahunAjaran(int userId, String idTA, String tahun_ajaran, String gen) {
        initComponents();
        this.idTA = idTA;
        this.tahun_ajaran = tahun_ajaran;
        this.gen = gen;
        this.userId = userId;

        tahunAjaranID.setText(idTA);
        tahunAjaran.setText(tahun_ajaran);
        genText.setText(gen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tahunAjaranID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tahunAjaran = new javax.swing.JTextField();
        btnKirimDataGuru = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        genText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UPDATE DATA TAHUN AJARAN");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel3.setText("ID TA");

        tahunAjaranID.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        tahunAjaranID.setForeground(new java.awt.Color(153, 153, 153));
        tahunAjaranID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tahunAjaranIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahunAjaranIDFocusLost(evt);
            }
        });
        tahunAjaranID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunAjaranIDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel4.setText("TAHUN AJARAN");

        tahunAjaran.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        tahunAjaran.setForeground(new java.awt.Color(153, 153, 153));
        tahunAjaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tahunAjaranFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tahunAjaranFocusLost(evt);
            }
        });
        tahunAjaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunAjaranActionPerformed(evt);
            }
        });

        btnKirimDataGuru.setBackground(new java.awt.Color(0, 102, 102));
        btnKirimDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        btnKirimDataGuru.setText("SUBMIT");
        btnKirimDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimDataGuruActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        genText.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        genText.setForeground(new java.awt.Color(153, 153, 153));
        genText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                genTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                genTextFocusLost(evt);
            }
        });
        genText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel5.setText("GEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnKirimDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(genText)
                            .addComponent(tahunAjaranID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tahunAjaran, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunAjaranID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tahunAjaran, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKirimDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tahunAjaranIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunAjaranIDFocusGained

    }//GEN-LAST:event_tahunAjaranIDFocusGained

    private void tahunAjaranIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunAjaranIDFocusLost

    }//GEN-LAST:event_tahunAjaranIDFocusLost

    private void tahunAjaranIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunAjaranIDActionPerformed
        //
    }//GEN-LAST:event_tahunAjaranIDActionPerformed

    private void tahunAjaranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunAjaranFocusGained

    }//GEN-LAST:event_tahunAjaranFocusGained

    private void tahunAjaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tahunAjaranFocusLost

    }//GEN-LAST:event_tahunAjaranFocusLost

    private void tahunAjaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunAjaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunAjaranActionPerformed

    private void btnKirimDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimDataGuruActionPerformed
//        UpdateDataTahunAjaran();
    }//GEN-LAST:event_btnKirimDataGuruActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void genTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genTextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_genTextFocusGained

    private void genTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_genTextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_genTextFocusLost

    private void genTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genTextActionPerformed

//    private void updateDataTA() {
//        String query = "UPDATE tahun_ajaran SET gen = ?, tahun_ajaran = ? WHERE id = ?";
//
//        try (Connection conn = koneksi.koneksiDB(); PreparedStatement preparedStatement = conn.prepareStatement(query)) {
//            preparedStatement.setString(2, mapelID.getText());
//            preparedStatement.setString(1, mpelName.getText());
//
//            System.out.println(idMapel);
//            int rowsUpdated = preparedStatement.executeUpdate();
//            if (rowsUpdated > 0) {
//                JOptionPane.showMessageDialog(this, "Data mapel berhasil diperbarui. Harap refresh halaman data mapel", "Success", JOptionPane.INFORMATION_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(this, "Gagal memperbarui data mapel. ID tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (SQLException e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Gagal memperbarui data mapel.", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDataTahunAjaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDataTahunAjaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDataTahunAjaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDataTahunAjaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new UpdateDataTahunAjaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnKirimDataGuru;
    private javax.swing.JTextField genText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tahunAjaran;
    private javax.swing.JTextField tahunAjaranID;
    // End of variables declaration//GEN-END:variables
}
