package TataUsaha.Input;

import TataUsaha.HomeTataUsaha;
import controllers.InputDataGuruController;
import java.awt.Color;
import models.InputDataGuruModel;
import javax.swing.JOptionPane;

public class InputDataGuru extends javax.swing.JFrame {

    private HomeTataUsaha homeFrame;
    private InputDataGuruController controller;
    private int userId;
    private String userName;

    public InputDataGuru(HomeTataUsaha homeFrame, String userName, int userId) {
        initComponents();
        this.homeFrame = homeFrame;
        this.userName = userName;
        this.userId = userId;
        controller = new InputDataGuruController();
        user.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nipGuru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namaGuru = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailGuru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordGuru = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        mapelGuru = new javax.swing.JComboBox<>();
        btnKirimDataGuru = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        user = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INPUT DATA SISWA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT DATA GURU");

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INPUT DATA GURU");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("NIP");

        nipGuru.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        nipGuru.setForeground(new java.awt.Color(153, 153, 153));
        nipGuru.setText("Masukkan NIP Guru");
        nipGuru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nipGuruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nipGuruFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("NAMA");

        namaGuru.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        namaGuru.setForeground(new java.awt.Color(153, 153, 153));
        namaGuru.setText("Masukkan Nama Guru");
        namaGuru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaGuruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namaGuruFocusLost(evt);
            }
        });
        namaGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaGuruActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("EMAIL");

        emailGuru.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        emailGuru.setForeground(new java.awt.Color(153, 153, 153));
        emailGuru.setText("Masukkan Email Guru");
        emailGuru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailGuruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailGuruFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");

        passwordGuru.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        passwordGuru.setForeground(new java.awt.Color(153, 153, 153));
        passwordGuru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordGuruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordGuruFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setText("GURU MAPEL");

        mapelGuru.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        mapelGuru.setForeground(new java.awt.Color(153, 153, 153));
        mapelGuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PBT", "PPB", "PWB", "BSD" }));

        btnKirimDataGuru.setBackground(new java.awt.Color(0, 102, 102));
        btnKirimDataGuru.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnKirimDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        btnKirimDataGuru.setText("SUBMIT");
        btnKirimDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimDataGuruActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        user.setText("name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nipGuru, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaGuru, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailGuru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                            .addComponent(passwordGuru, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mapelGuru, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnKirimDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nipGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(namaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mapelGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKirimDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nipGuruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nipGuruFocusGained
        if (nipGuru.getText().equals("Masukkan NIP Guru")) {
            nipGuru.setText("");
            nipGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nipGuruFocusGained

    private void nipGuruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nipGuruFocusLost
        if (nipGuru.getText().equals("")) {
            nipGuru.setText("Masukkan NIP Guru");
            nipGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nipGuruFocusLost

    private void namaGuruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaGuruFocusGained
        if (namaGuru.getText().equals("Masukkan Nama Guru")) {
            namaGuru.setText("");
            namaGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_namaGuruFocusGained

    private void namaGuruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaGuruFocusLost
        if (namaGuru.getText().equals("")) {
            namaGuru.setText("Masukkan Nama Guru");
            namaGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_namaGuruFocusLost

    private void emailGuruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailGuruFocusGained
        if (emailGuru.getText().equals("Masukkan Email Guru")) {
            emailGuru.setText("");
            emailGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailGuruFocusGained

    private void emailGuruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailGuruFocusLost
        if (emailGuru.getText().equals("")) {
            emailGuru.setText("Masukkan Email Guru");
            emailGuru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailGuruFocusLost

    private void namaGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaGuruActionPerformed

    private void btnKirimDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimDataGuruActionPerformed
        String nip = nipGuru.getText();
        String nama = namaGuru.getText();
        String email = emailGuru.getText();
        String password = passwordGuru.getText();
        String selectedMapel = (String) mapelGuru.getSelectedItem();

        InputDataGuruModel guru = new InputDataGuruModel(nip, nama, email, password, selectedMapel);

        boolean success = controller.insertDataGuru(guru);
        if (success) {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Success", JOptionPane.INFORMATION_MESSAGE);
            nipGuru.setText("");
            namaGuru.setText("");
            emailGuru.setText("");
            passwordGuru.setText("");
            mapelGuru.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_btnKirimDataGuruActionPerformed

    private void passwordGuruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordGuruFocusGained

    }//GEN-LAST:event_passwordGuruFocusGained

    private void passwordGuruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordGuruFocusLost

    }//GEN-LAST:event_passwordGuruFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String hariDiPilih = homeFrame.getComboBoxHari().getSelectedItem().toString();
        homeFrame.setVisible(true);
        homeFrame.loadJadwalData(hariDiPilih);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                HomeTataUsaha homeFrame = new HomeTataUsaha();
//                String userName = "NamaPenggunaTest";
//                int userId = 1;
//                new InputDataGuru(homeFrame, userName, userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnKirimDataGuru;
    private javax.swing.JTextField emailGuru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mapelGuru;
    private javax.swing.JTextField namaGuru;
    private javax.swing.JTextField nipGuru;
    private javax.swing.JPasswordField passwordGuru;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
