/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TataUsaha.Input;

import TataUsaha.HomeTataUsaha;
import koneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Achmad
 */
public class InputDataKelas extends javax.swing.JFrame {

    /**
     * Creates new form InputDataKelas
     */
    private HomeTataUsaha homeFrame;

    public InputDataKelas(HomeTataUsaha homeFrame, String userName, int userId) {
        initComponents();
        this.homeFrame = homeFrame;
        this.userName = userName;
        this.userId = userId;
        user.setText(userName);
        loadComboBoxes();
    }

    private int roleId;

    public int getRoleId() {
        return roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    //    BARU 1
    private int userId;
    private String userName;

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    private void loadComboBoxes() {
        loadGenComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaKelas = new javax.swing.JComboBox<>();
        namaJurusan = new javax.swing.JComboBox<>();
        genSiswa = new javax.swing.JComboBox<>();
        btnKirimDataKelas = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INPUT DATA KELAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaKelas.setBackground(new java.awt.Color(255, 255, 255));
        namaKelas.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        namaKelas.setForeground(new java.awt.Color(60, 63, 65));
        namaKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL 1", "RPL 2" }));
        namaKelas.setBorder(null);
        getContentPane().add(namaKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 195, 550, 22));

        namaJurusan.setBackground(new java.awt.Color(255, 255, 255));
        namaJurusan.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        namaJurusan.setForeground(new java.awt.Color(60, 63, 65));
        namaJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rekayasa Perangkat Lunak" }));
        namaJurusan.setBorder(null);
        getContentPane().add(namaJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 550, 22));

        genSiswa.setBackground(new java.awt.Color(255, 255, 255));
        genSiswa.setForeground(new java.awt.Color(60, 63, 65));
        genSiswa.setBorder(null);
        getContentPane().add(genSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 366, 550, 22));

        btnKirimDataKelas.setBackground(new java.awt.Color(0, 102, 102));
        btnKirimDataKelas.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnKirimDataKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnKirimDataKelas.setText("SUBMIT");
        btnKirimDataKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimDataKelasActionPerformed(evt);
            }
        });
        getContentPane().add(btnKirimDataKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 459, 99, 42));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 458, 100, 44));

        user.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        user.setForeground(new java.awt.Color(60, 63, 65));
        user.setText("name");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/InputDataKelas.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadGenComboBox() {
        String query = "SELECT id, gen FROM tahun_ajaran";

        try (Connection conn = (Connection) koneksi.koneksiDB(); PreparedStatement preparedStatement = conn.prepareStatement(query); ResultSet resultSet = preparedStatement.executeQuery(query)) {

            genSiswa.removeAllItems();
            while (resultSet.next()) {
                String genId = resultSet.getString("id");
                String gen = resultSet.getString("gen");
                genSiswa.addItem(genId + " - " + gen);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data gen", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void insertDataKelas() {
        String selectedKelas = (String) namaKelas.getSelectedItem();
        String selectedJurusan = (String) namaJurusan.getSelectedItem();

        String selectedGen = (String) genSiswa.getSelectedItem();
        String genId = selectedGen.split(" - ")[0];

        String query = "INSERT INTO kelas (nama_kelas, jurusan, gen_id) VALUES (?, ?, ?)";

        try (Connection conn = (Connection) koneksi.koneksiDB(); PreparedStatement preparedStatement = conn.prepareStatement(query)) {
            preparedStatement.setString(1, selectedKelas);
            preparedStatement.setString(2, selectedJurusan);
            preparedStatement.setInt(3, Integer.parseInt(genId));

            int rowsInserted = preparedStatement.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Success", JOptionPane.INFORMATION_MESSAGE);
                namaKelas.setSelectedIndex(-1);
                namaJurusan.setSelectedIndex(-1);
                genSiswa.setSelectedIndex(-1);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String hariDiPilih = homeFrame.getComboBoxHari().getSelectedItem().toString();
        homeFrame.setVisible(true);
        homeFrame.loadJadwalData(hariDiPilih);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnKirimDataKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimDataKelasActionPerformed
        insertDataKelas();
    }//GEN-LAST:event_btnKirimDataKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                HomeTataUsaha homeFrame = new HomeTataUsaha();
//                String userName = "NamaPenggunaTest";
//                int userId = 1;
//                new InputDataKelas(homeFrame, userName, userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnKirimDataKelas;
    private javax.swing.JComboBox<String> genSiswa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> namaJurusan;
    private javax.swing.JComboBox<String> namaKelas;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
